module.exports = {
    prefix: 'tw-',
    darkMode: false, // or 'media' or 'class'
    theme: {
      extend: {
        padding: {
          sx: "10px",
          sm: "15px",
          md: "20px",
          25: "25px",
          lg: "40px",
          xlg: "80px",
        },
        margin: {
          sx: "10px",
          sm: "15px",
          md: "20px",
          25: "25px",
          lg: "40px",
          xlg: "80px",
        },
        screens: {
          tablet: "431px",
          desktop: "770px",
        },
        colors: {
          fresh: "#00bf6f",
          white: "#fff",
          black: "#000",
          gray: "#f2f4f7",
          navy: "#00263e",
          blue: "#1d3a6c",
          yellow: "#ffbf00",
          protein: "#c44c42",
          proteinDark: "#a90000",
          paleo: "#ce762f",
          paleoDark: "#c05200",
          keto: "#ffb500",
          ketoDark: "#da8c00",
          vegan: "#7a9560",
          veganDark: "#425a31",
          veganlc: "#6e9dd6",
          veganlcDark: "#4b6aa5",
          whole30: "#60b5c1",
          whole30Dark: "#4c8f98",
          whole30Light: "#dcecef",
          mediterranean: "#093ac1",
          mediterraneanDark: "#002ca3",
          mediterraneanLight: "#c6d5ff",
          preheader: "#8F95A3",
          loginInput: "#445574",
          footerbg: "#F2F4F7",
          error: "#f8d2d2",
          errorDark: "#ce2f2f",
          warning: "#FFF5D5",
          warningDark: "#CE7630",
          gray1: "#D7DAE1",
          navBorder: "#bcc2d1",
          rust: "#BF0000",
        },
        content: ["./src/**/*.{html,js}"],
      },
    },
    variants: {
      extend: {},
    },
    plugins: [],
  };
  